#!/bin/bash


set -e

LINK_TO_SAVE="$1"
FILENAME=$(basename "${LINK_TO_SAVE}")


mv "${LINK_TO_SAVE}" "${HOME}/repo/linux_setup/${FILENAME}"
ln -s "${HOME}/repo/linux_setup/${FILENAME}" "${LINK_TO_SAVE}"

CMD="ln -s '${HOME}/repo/linux_setup/${FILENAME}' '${LINK_TO_SAVE}'"


echo "Save ${CMD}"
echo "${CMD}" >> setup.sh

# I need an absolute path to move it to
# or just assume everything is within user folder

# move file to dotfiles
# create link to original location
# add it to permanent registry


